fixing TC build errors:
Shipping\ShippingSettings.cs(46, 68): error CS0103: The name 'nameof' does not exist in the current context
Shipping\ShippingSettings.cs(47, 70): error CS0103: The name 'nameof' does not exist in the current context